/*
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.ui;

import com.google.inject.Injector;
import edu.ustb.cmp.minijava.ui.internal.MinijavaActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MiniJavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MinijavaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MinijavaActivator activator = MinijavaActivator.getInstance();
		return activator != null ? activator.getInjector(MinijavaActivator.EDU_USTB_CMP_MINIJAVA) : null;
	}

}
