/*
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.ustb.cmp.MiniJavaRuntimeModule;
import edu.ustb.cmp.MiniJavaStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MiniJavaIdeSetup extends MiniJavaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MiniJavaRuntimeModule(), new MiniJavaIdeModule()));
	}
	
}
