/*
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MiniJavaStandaloneSetup extends MiniJavaStandaloneSetupGenerated {

	public static void doSetup() {
		new MiniJavaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
