/*
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MiniJavaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/ustb/cmp/parser/antlr/internal/InternalMiniJava.tokens");
	}
}
