/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calc Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.cmp.miniJava.CalcExp#getLeftName <em>Left Name</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.CalcExp#getLeftNum <em>Left Num</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.CalcExp#getOp <em>Op</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.CalcExp#getRightName <em>Right Name</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.CalcExp#getRightNum <em>Right Num</em>}</li>
 * </ul>
 *
 * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getCalcExp()
 * @model
 * @generated
 */
public interface CalcExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Left Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Name</em>' attribute.
   * @see #setLeftName(String)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getCalcExp_LeftName()
   * @model
   * @generated
   */
  String getLeftName();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.CalcExp#getLeftName <em>Left Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Name</em>' attribute.
   * @see #getLeftName()
   * @generated
   */
  void setLeftName(String value);

  /**
   * Returns the value of the '<em><b>Left Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Num</em>' attribute.
   * @see #setLeftNum(int)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getCalcExp_LeftNum()
   * @model
   * @generated
   */
  int getLeftNum();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.CalcExp#getLeftNum <em>Left Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Num</em>' attribute.
   * @see #getLeftNum()
   * @generated
   */
  void setLeftNum(int value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getCalcExp_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.CalcExp#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Name</em>' attribute.
   * @see #setRightName(String)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getCalcExp_RightName()
   * @model
   * @generated
   */
  String getRightName();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.CalcExp#getRightName <em>Right Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Name</em>' attribute.
   * @see #getRightName()
   * @generated
   */
  void setRightName(String value);

  /**
   * Returns the value of the '<em><b>Right Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Num</em>' attribute.
   * @see #setRightNum(int)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getCalcExp_RightNum()
   * @model
   * @generated
   */
  int getRightNum();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.CalcExp#getRightNum <em>Right Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Num</em>' attribute.
   * @see #getRightNum()
   * @generated
   */
  void setRightNum(int value);

} // CalcExp
