/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.cmp.miniJava.Expression#getStatements <em>Statements</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Expression#getElseIf <em>Else If</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Expression#getElse <em>Else</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Expression#getConst <em>Const</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Expression#getCe <em>Ce</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Expression#getJe <em>Je</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Expression#getNe <em>Ne</em>}</li>
 * </ul>
 *
 * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends IfStatements, ElseIfStatements, WhileStatements
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link edu.ustb.cmp.miniJava.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getExpression_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

  /**
   * Returns the value of the '<em><b>Else If</b></em>' containment reference list.
   * The list contents are of type {@link edu.ustb.cmp.miniJava.ElseIfStatements}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else If</em>' containment reference list.
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getExpression_ElseIf()
   * @model containment="true"
   * @generated
   */
  EList<ElseIfStatements> getElseIf();

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference list.
   * The list contents are of type {@link edu.ustb.cmp.miniJava.ElseStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference list.
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getExpression_Else()
   * @model containment="true"
   * @generated
   */
  EList<ElseStatement> getElse();

  /**
   * Returns the value of the '<em><b>Const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const</em>' attribute.
   * @see #setConst(String)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getExpression_Const()
   * @model
   * @generated
   */
  String getConst();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Expression#getConst <em>Const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const</em>' attribute.
   * @see #getConst()
   * @generated
   */
  void setConst(String value);

  /**
   * Returns the value of the '<em><b>Ce</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ce</em>' containment reference.
   * @see #setCe(CalcExp)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getExpression_Ce()
   * @model containment="true"
   * @generated
   */
  CalcExp getCe();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Expression#getCe <em>Ce</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ce</em>' containment reference.
   * @see #getCe()
   * @generated
   */
  void setCe(CalcExp value);

  /**
   * Returns the value of the '<em><b>Je</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Je</em>' containment reference.
   * @see #setJe(JudgeExp)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getExpression_Je()
   * @model containment="true"
   * @generated
   */
  JudgeExp getJe();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Expression#getJe <em>Je</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Je</em>' containment reference.
   * @see #getJe()
   * @generated
   */
  void setJe(JudgeExp value);

  /**
   * Returns the value of the '<em><b>Ne</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ne</em>' containment reference.
   * @see #setNe(NewExp)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getExpression_Ne()
   * @model containment="true"
   * @generated
   */
  NewExp getNe();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Expression#getNe <em>Ne</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ne</em>' containment reference.
   * @see #getNe()
   * @generated
   */
  void setNe(NewExp value);

} // Expression
