/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Judge Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.cmp.miniJava.JudgeExp#getBj <em>Bj</em>}</li>
 * </ul>
 *
 * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getJudgeExp()
 * @model
 * @generated
 */
public interface JudgeExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Bj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bj</em>' containment reference.
   * @see #setBj(BasicJudge)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getJudgeExp_Bj()
   * @model containment="true"
   * @generated
   */
  BasicJudge getBj();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.JudgeExp#getBj <em>Bj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bj</em>' containment reference.
   * @see #getBj()
   * @generated
   */
  void setBj(BasicJudge value);

} // JudgeExp
