/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mini Java</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.cmp.miniJava.MiniJava#getPackage <em>Package</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.MiniJava#getImports <em>Imports</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.MiniJava#getMainclass <em>Mainclass</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.MiniJava#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getMiniJava()
 * @model
 * @generated
 */
public interface MiniJava extends EObject
{
  /**
   * Returns the value of the '<em><b>Package</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' containment reference.
   * @see #setPackage(PackageDecl)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getMiniJava_Package()
   * @model containment="true"
   * @generated
   */
  PackageDecl getPackage();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.MiniJava#getPackage <em>Package</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package</em>' containment reference.
   * @see #getPackage()
   * @generated
   */
  void setPackage(PackageDecl value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link edu.ustb.cmp.miniJava.ImportDecl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getMiniJava_Imports()
   * @model containment="true"
   * @generated
   */
  EList<ImportDecl> getImports();

  /**
   * Returns the value of the '<em><b>Mainclass</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mainclass</em>' containment reference.
   * @see #setMainclass(MainClassDecl)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getMiniJava_Mainclass()
   * @model containment="true"
   * @generated
   */
  MainClassDecl getMainclass();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.MiniJava#getMainclass <em>Mainclass</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mainclass</em>' containment reference.
   * @see #getMainclass()
   * @generated
   */
  void setMainclass(MainClassDecl value);

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link edu.ustb.cmp.miniJava.ClassDecl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getMiniJava_Classes()
   * @model containment="true"
   * @generated
   */
  EList<ClassDecl> getClasses();

} // MiniJava
