/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.ustb.cmp.miniJava.MiniJavaFactory
 * @model kind="package"
 * @generated
 */
public interface MiniJavaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "miniJava";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ustb.edu/cmp/MiniJava";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "miniJava";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MiniJavaPackage eINSTANCE = edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.MiniJavaImpl <em>Mini Java</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getMiniJava()
   * @generated
   */
  int MINI_JAVA = 0;

  /**
   * The feature id for the '<em><b>Package</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINI_JAVA__PACKAGE = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINI_JAVA__IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Mainclass</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINI_JAVA__MAINCLASS = 2;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINI_JAVA__CLASSES = 3;

  /**
   * The number of structural features of the '<em>Mini Java</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINI_JAVA_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.PackageDeclImpl <em>Package Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.PackageDeclImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getPackageDecl()
   * @generated
   */
  int PACKAGE_DECL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECL__NAME = 0;

  /**
   * The number of structural features of the '<em>Package Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.ImportDeclImpl <em>Import Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.ImportDeclImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getImportDecl()
   * @generated
   */
  int IMPORT_DECL = 2;

  /**
   * The feature id for the '<em><b>Anchor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_DECL__ANCHOR = 0;

  /**
   * The number of structural features of the '<em>Import Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_DECL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.MainClassDeclImpl <em>Main Class Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.MainClassDeclImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getMainClassDecl()
   * @generated
   */
  int MAIN_CLASS_DECL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_CLASS_DECL__NAME = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_CLASS_DECL__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Main Class Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_CLASS_DECL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.ClassDeclImpl <em>Class Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.ClassDeclImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getClassDecl()
   * @generated
   */
  int CLASS_DECL = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL__NAME = 0;

  /**
   * The feature id for the '<em><b>Super Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL__SUPER_CLASS = 1;

  /**
   * The feature id for the '<em><b>Implementz</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL__IMPLEMENTZ = 2;

  /**
   * The feature id for the '<em><b>Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL__MEMBERS = 3;

  /**
   * The number of structural features of the '<em>Class Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.MemberImpl <em>Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.MemberImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getMember()
   * @generated
   */
  int MEMBER = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER__NAME = 0;

  /**
   * The number of structural features of the '<em>Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.VariableDeclImpl <em>Variable Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.VariableDeclImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getVariableDecl()
   * @generated
   */
  int VARIABLE_DECL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL__NAME = MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Var Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL__VAR_TYPE = MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL__VALUE = MEMBER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECL_FEATURE_COUNT = MEMBER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.ParameterImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.MethodDeclImpl <em>Method Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.MethodDeclImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getMethodDecl()
   * @generated
   */
  int METHOD_DECL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECL__NAME = MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Domain</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECL__DOMAIN = MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Extra</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECL__EXTRA = MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ret Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECL__RET_TYPE = MEMBER_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECL__PARAMS = MEMBER_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECL__STATEMENTS = MEMBER_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Method Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DECL_FEATURE_COUNT = MEMBER_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.StatementImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Var Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__VAR_DEF = 0;

  /**
   * The feature id for the '<em><b>Assign</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__ASSIGN = 1;

  /**
   * The feature id for the '<em><b>If Stat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__IF_STAT = 2;

  /**
   * The feature id for the '<em><b>While Stat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__WHILE_STAT = 3;

  /**
   * The feature id for the '<em><b>Ret Stat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__RET_STAT = 4;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.LValueExpImpl <em>LValue Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.LValueExpImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getLValueExp()
   * @generated
   */
  int LVALUE_EXP = 10;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LVALUE_EXP__ID = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LVALUE_EXP__EXP = 1;

  /**
   * The feature id for the '<em><b>Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LVALUE_EXP__INDEX = 2;

  /**
   * The number of structural features of the '<em>LValue Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LVALUE_EXP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.AssignmentsImpl <em>Assignments</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.AssignmentsImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getAssignments()
   * @generated
   */
  int ASSIGNMENTS = 11;

  /**
   * The feature id for the '<em><b>Left Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENTS__LEFT_VALUE = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENTS__EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Assignments</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.IfStatementsImpl <em>If Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.IfStatementsImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getIfStatements()
   * @generated
   */
  int IF_STATEMENTS = 12;

  /**
   * The number of structural features of the '<em>If Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENTS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.ElseIfStatementsImpl <em>Else If Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.ElseIfStatementsImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getElseIfStatements()
   * @generated
   */
  int ELSE_IF_STATEMENTS = 13;

  /**
   * The number of structural features of the '<em>Else If Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELSE_IF_STATEMENTS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.ElseStatementImpl <em>Else Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.ElseStatementImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getElseStatement()
   * @generated
   */
  int ELSE_STATEMENT = 14;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELSE_STATEMENT__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Else Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELSE_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.WhileStatementsImpl <em>While Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.WhileStatementsImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getWhileStatements()
   * @generated
   */
  int WHILE_STATEMENTS = 15;

  /**
   * The number of structural features of the '<em>While Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_STATEMENTS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.ReturnStatementsImpl <em>Return Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.ReturnStatementsImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getReturnStatements()
   * @generated
   */
  int RETURN_STATEMENTS = 16;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_STATEMENTS__EXP = 0;

  /**
   * The number of structural features of the '<em>Return Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_STATEMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.CalcExpImpl <em>Calc Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.CalcExpImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getCalcExp()
   * @generated
   */
  int CALC_EXP = 17;

  /**
   * The feature id for the '<em><b>Left Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALC_EXP__LEFT_NAME = 0;

  /**
   * The feature id for the '<em><b>Left Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALC_EXP__LEFT_NUM = 1;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALC_EXP__OP = 2;

  /**
   * The feature id for the '<em><b>Right Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALC_EXP__RIGHT_NAME = 3;

  /**
   * The feature id for the '<em><b>Right Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALC_EXP__RIGHT_NUM = 4;

  /**
   * The number of structural features of the '<em>Calc Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALC_EXP_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.CompareExpImpl <em>Compare Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.CompareExpImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getCompareExp()
   * @generated
   */
  int COMPARE_EXP = 18;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE_EXP__ID = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE_EXP__OP = 1;

  /**
   * The feature id for the '<em><b>Other1</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE_EXP__OTHER1 = 2;

  /**
   * The feature id for the '<em><b>Other2</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE_EXP__OTHER2 = 3;

  /**
   * The number of structural features of the '<em>Compare Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE_EXP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.BasicJudgeImpl <em>Basic Judge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.BasicJudgeImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getBasicJudge()
   * @generated
   */
  int BASIC_JUDGE = 19;

  /**
   * The feature id for the '<em><b>BE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_JUDGE__BE = 0;

  /**
   * The feature id for the '<em><b>Cmp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_JUDGE__CMP = 1;

  /**
   * The number of structural features of the '<em>Basic Judge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_JUDGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.JudgeExpImpl <em>Judge Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.JudgeExpImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getJudgeExp()
   * @generated
   */
  int JUDGE_EXP = 20;

  /**
   * The feature id for the '<em><b>Bj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JUDGE_EXP__BJ = 0;

  /**
   * The number of structural features of the '<em>Judge Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JUDGE_EXP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.NewExpImpl <em>New Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.NewExpImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getNewExp()
   * @generated
   */
  int NEW_EXP = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_EXP__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_EXP__PARAMS = 1;

  /**
   * The number of structural features of the '<em>New Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_EXP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.impl.ExpressionImpl
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 22;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__STATEMENTS = IF_STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Else If</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ELSE_IF = IF_STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ELSE = IF_STATEMENTS_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__CONST = IF_STATEMENTS_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Ce</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__CE = IF_STATEMENTS_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Je</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__JE = IF_STATEMENTS_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Ne</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NE = IF_STATEMENTS_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = IF_STATEMENTS_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.Domain <em>Domain</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.Domain
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getDomain()
   * @generated
   */
  int DOMAIN = 23;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.ExtraAttr <em>Extra Attr</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.ExtraAttr
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getExtraAttr()
   * @generated
   */
  int EXTRA_ATTR = 24;

  /**
   * The meta object id for the '{@link edu.ustb.cmp.miniJava.BooleanExp <em>Boolean Exp</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ustb.cmp.miniJava.BooleanExp
   * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getBooleanExp()
   * @generated
   */
  int BOOLEAN_EXP = 25;


  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.MiniJava <em>Mini Java</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mini Java</em>'.
   * @see edu.ustb.cmp.miniJava.MiniJava
   * @generated
   */
  EClass getMiniJava();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.MiniJava#getPackage <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Package</em>'.
   * @see edu.ustb.cmp.miniJava.MiniJava#getPackage()
   * @see #getMiniJava()
   * @generated
   */
  EReference getMiniJava_Package();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.MiniJava#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see edu.ustb.cmp.miniJava.MiniJava#getImports()
   * @see #getMiniJava()
   * @generated
   */
  EReference getMiniJava_Imports();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.MiniJava#getMainclass <em>Mainclass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mainclass</em>'.
   * @see edu.ustb.cmp.miniJava.MiniJava#getMainclass()
   * @see #getMiniJava()
   * @generated
   */
  EReference getMiniJava_Mainclass();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.MiniJava#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see edu.ustb.cmp.miniJava.MiniJava#getClasses()
   * @see #getMiniJava()
   * @generated
   */
  EReference getMiniJava_Classes();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.PackageDecl <em>Package Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Decl</em>'.
   * @see edu.ustb.cmp.miniJava.PackageDecl
   * @generated
   */
  EClass getPackageDecl();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.PackageDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ustb.cmp.miniJava.PackageDecl#getName()
   * @see #getPackageDecl()
   * @generated
   */
  EAttribute getPackageDecl_Name();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.ImportDecl <em>Import Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Decl</em>'.
   * @see edu.ustb.cmp.miniJava.ImportDecl
   * @generated
   */
  EClass getImportDecl();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.ImportDecl#getAnchor <em>Anchor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Anchor</em>'.
   * @see edu.ustb.cmp.miniJava.ImportDecl#getAnchor()
   * @see #getImportDecl()
   * @generated
   */
  EAttribute getImportDecl_Anchor();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.MainClassDecl <em>Main Class Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main Class Decl</em>'.
   * @see edu.ustb.cmp.miniJava.MainClassDecl
   * @generated
   */
  EClass getMainClassDecl();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.MainClassDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ustb.cmp.miniJava.MainClassDecl#getName()
   * @see #getMainClassDecl()
   * @generated
   */
  EAttribute getMainClassDecl_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.MainClassDecl#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see edu.ustb.cmp.miniJava.MainClassDecl#getStatements()
   * @see #getMainClassDecl()
   * @generated
   */
  EReference getMainClassDecl_Statements();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.ClassDecl <em>Class Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Decl</em>'.
   * @see edu.ustb.cmp.miniJava.ClassDecl
   * @generated
   */
  EClass getClassDecl();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.ClassDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ustb.cmp.miniJava.ClassDecl#getName()
   * @see #getClassDecl()
   * @generated
   */
  EAttribute getClassDecl_Name();

  /**
   * Returns the meta object for the reference '{@link edu.ustb.cmp.miniJava.ClassDecl#getSuperClass <em>Super Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Class</em>'.
   * @see edu.ustb.cmp.miniJava.ClassDecl#getSuperClass()
   * @see #getClassDecl()
   * @generated
   */
  EReference getClassDecl_SuperClass();

  /**
   * Returns the meta object for the reference list '{@link edu.ustb.cmp.miniJava.ClassDecl#getImplementz <em>Implementz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Implementz</em>'.
   * @see edu.ustb.cmp.miniJava.ClassDecl#getImplementz()
   * @see #getClassDecl()
   * @generated
   */
  EReference getClassDecl_Implementz();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.ClassDecl#getMembers <em>Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Members</em>'.
   * @see edu.ustb.cmp.miniJava.ClassDecl#getMembers()
   * @see #getClassDecl()
   * @generated
   */
  EReference getClassDecl_Members();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.VariableDecl <em>Variable Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Decl</em>'.
   * @see edu.ustb.cmp.miniJava.VariableDecl
   * @generated
   */
  EClass getVariableDecl();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.VariableDecl#getVarType <em>Var Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var Type</em>'.
   * @see edu.ustb.cmp.miniJava.VariableDecl#getVarType()
   * @see #getVariableDecl()
   * @generated
   */
  EAttribute getVariableDecl_VarType();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.VariableDecl#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.ustb.cmp.miniJava.VariableDecl#getValue()
   * @see #getVariableDecl()
   * @generated
   */
  EAttribute getVariableDecl_Value();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see edu.ustb.cmp.miniJava.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see edu.ustb.cmp.miniJava.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Type();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ustb.cmp.miniJava.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.MethodDecl <em>Method Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Decl</em>'.
   * @see edu.ustb.cmp.miniJava.MethodDecl
   * @generated
   */
  EClass getMethodDecl();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.MethodDecl#getDomain <em>Domain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Domain</em>'.
   * @see edu.ustb.cmp.miniJava.MethodDecl#getDomain()
   * @see #getMethodDecl()
   * @generated
   */
  EAttribute getMethodDecl_Domain();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.MethodDecl#getExtra <em>Extra</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Extra</em>'.
   * @see edu.ustb.cmp.miniJava.MethodDecl#getExtra()
   * @see #getMethodDecl()
   * @generated
   */
  EAttribute getMethodDecl_Extra();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.MethodDecl#getRetType <em>Ret Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ret Type</em>'.
   * @see edu.ustb.cmp.miniJava.MethodDecl#getRetType()
   * @see #getMethodDecl()
   * @generated
   */
  EAttribute getMethodDecl_RetType();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.MethodDecl#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see edu.ustb.cmp.miniJava.MethodDecl#getParams()
   * @see #getMethodDecl()
   * @generated
   */
  EReference getMethodDecl_Params();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.MethodDecl#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see edu.ustb.cmp.miniJava.MethodDecl#getStatements()
   * @see #getMethodDecl()
   * @generated
   */
  EReference getMethodDecl_Statements();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.Member <em>Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Member</em>'.
   * @see edu.ustb.cmp.miniJava.Member
   * @generated
   */
  EClass getMember();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.Member#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ustb.cmp.miniJava.Member#getName()
   * @see #getMember()
   * @generated
   */
  EAttribute getMember_Name();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see edu.ustb.cmp.miniJava.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Statement#getVarDef <em>Var Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var Def</em>'.
   * @see edu.ustb.cmp.miniJava.Statement#getVarDef()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_VarDef();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Statement#getAssign <em>Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Assign</em>'.
   * @see edu.ustb.cmp.miniJava.Statement#getAssign()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Assign();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Statement#getIfStat <em>If Stat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If Stat</em>'.
   * @see edu.ustb.cmp.miniJava.Statement#getIfStat()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_IfStat();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Statement#getWhileStat <em>While Stat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>While Stat</em>'.
   * @see edu.ustb.cmp.miniJava.Statement#getWhileStat()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_WhileStat();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Statement#getRetStat <em>Ret Stat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ret Stat</em>'.
   * @see edu.ustb.cmp.miniJava.Statement#getRetStat()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_RetStat();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.LValueExp <em>LValue Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LValue Exp</em>'.
   * @see edu.ustb.cmp.miniJava.LValueExp
   * @generated
   */
  EClass getLValueExp();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.LValueExp#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see edu.ustb.cmp.miniJava.LValueExp#getId()
   * @see #getLValueExp()
   * @generated
   */
  EAttribute getLValueExp_Id();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.LValueExp#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see edu.ustb.cmp.miniJava.LValueExp#getExp()
   * @see #getLValueExp()
   * @generated
   */
  EReference getLValueExp_Exp();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.LValueExp#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Index</em>'.
   * @see edu.ustb.cmp.miniJava.LValueExp#getIndex()
   * @see #getLValueExp()
   * @generated
   */
  EReference getLValueExp_Index();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.Assignments <em>Assignments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignments</em>'.
   * @see edu.ustb.cmp.miniJava.Assignments
   * @generated
   */
  EClass getAssignments();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Assignments#getLeftValue <em>Left Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Value</em>'.
   * @see edu.ustb.cmp.miniJava.Assignments#getLeftValue()
   * @see #getAssignments()
   * @generated
   */
  EReference getAssignments_LeftValue();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Assignments#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see edu.ustb.cmp.miniJava.Assignments#getExpression()
   * @see #getAssignments()
   * @generated
   */
  EReference getAssignments_Expression();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.IfStatements <em>If Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Statements</em>'.
   * @see edu.ustb.cmp.miniJava.IfStatements
   * @generated
   */
  EClass getIfStatements();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.ElseIfStatements <em>Else If Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Else If Statements</em>'.
   * @see edu.ustb.cmp.miniJava.ElseIfStatements
   * @generated
   */
  EClass getElseIfStatements();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.ElseStatement <em>Else Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Else Statement</em>'.
   * @see edu.ustb.cmp.miniJava.ElseStatement
   * @generated
   */
  EClass getElseStatement();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.ElseStatement#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see edu.ustb.cmp.miniJava.ElseStatement#getStatements()
   * @see #getElseStatement()
   * @generated
   */
  EReference getElseStatement_Statements();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.WhileStatements <em>While Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Statements</em>'.
   * @see edu.ustb.cmp.miniJava.WhileStatements
   * @generated
   */
  EClass getWhileStatements();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.ReturnStatements <em>Return Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Return Statements</em>'.
   * @see edu.ustb.cmp.miniJava.ReturnStatements
   * @generated
   */
  EClass getReturnStatements();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.ReturnStatements#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see edu.ustb.cmp.miniJava.ReturnStatements#getExp()
   * @see #getReturnStatements()
   * @generated
   */
  EReference getReturnStatements_Exp();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.CalcExp <em>Calc Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Calc Exp</em>'.
   * @see edu.ustb.cmp.miniJava.CalcExp
   * @generated
   */
  EClass getCalcExp();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.CalcExp#getLeftName <em>Left Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left Name</em>'.
   * @see edu.ustb.cmp.miniJava.CalcExp#getLeftName()
   * @see #getCalcExp()
   * @generated
   */
  EAttribute getCalcExp_LeftName();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.CalcExp#getLeftNum <em>Left Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left Num</em>'.
   * @see edu.ustb.cmp.miniJava.CalcExp#getLeftNum()
   * @see #getCalcExp()
   * @generated
   */
  EAttribute getCalcExp_LeftNum();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.CalcExp#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ustb.cmp.miniJava.CalcExp#getOp()
   * @see #getCalcExp()
   * @generated
   */
  EAttribute getCalcExp_Op();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.CalcExp#getRightName <em>Right Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right Name</em>'.
   * @see edu.ustb.cmp.miniJava.CalcExp#getRightName()
   * @see #getCalcExp()
   * @generated
   */
  EAttribute getCalcExp_RightName();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.CalcExp#getRightNum <em>Right Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right Num</em>'.
   * @see edu.ustb.cmp.miniJava.CalcExp#getRightNum()
   * @see #getCalcExp()
   * @generated
   */
  EAttribute getCalcExp_RightNum();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.CompareExp <em>Compare Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compare Exp</em>'.
   * @see edu.ustb.cmp.miniJava.CompareExp
   * @generated
   */
  EClass getCompareExp();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.CompareExp#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see edu.ustb.cmp.miniJava.CompareExp#getId()
   * @see #getCompareExp()
   * @generated
   */
  EAttribute getCompareExp_Id();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.CompareExp#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ustb.cmp.miniJava.CompareExp#getOp()
   * @see #getCompareExp()
   * @generated
   */
  EAttribute getCompareExp_Op();

  /**
   * Returns the meta object for the attribute list '{@link edu.ustb.cmp.miniJava.CompareExp#getOther1 <em>Other1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Other1</em>'.
   * @see edu.ustb.cmp.miniJava.CompareExp#getOther1()
   * @see #getCompareExp()
   * @generated
   */
  EAttribute getCompareExp_Other1();

  /**
   * Returns the meta object for the attribute list '{@link edu.ustb.cmp.miniJava.CompareExp#getOther2 <em>Other2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Other2</em>'.
   * @see edu.ustb.cmp.miniJava.CompareExp#getOther2()
   * @see #getCompareExp()
   * @generated
   */
  EAttribute getCompareExp_Other2();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.BasicJudge <em>Basic Judge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Basic Judge</em>'.
   * @see edu.ustb.cmp.miniJava.BasicJudge
   * @generated
   */
  EClass getBasicJudge();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.BasicJudge#getBE <em>BE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>BE</em>'.
   * @see edu.ustb.cmp.miniJava.BasicJudge#getBE()
   * @see #getBasicJudge()
   * @generated
   */
  EAttribute getBasicJudge_BE();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.BasicJudge#getCmp <em>Cmp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmp</em>'.
   * @see edu.ustb.cmp.miniJava.BasicJudge#getCmp()
   * @see #getBasicJudge()
   * @generated
   */
  EReference getBasicJudge_Cmp();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.JudgeExp <em>Judge Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Judge Exp</em>'.
   * @see edu.ustb.cmp.miniJava.JudgeExp
   * @generated
   */
  EClass getJudgeExp();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.JudgeExp#getBj <em>Bj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bj</em>'.
   * @see edu.ustb.cmp.miniJava.JudgeExp#getBj()
   * @see #getJudgeExp()
   * @generated
   */
  EReference getJudgeExp_Bj();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.NewExp <em>New Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>New Exp</em>'.
   * @see edu.ustb.cmp.miniJava.NewExp
   * @generated
   */
  EClass getNewExp();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.NewExp#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ustb.cmp.miniJava.NewExp#getName()
   * @see #getNewExp()
   * @generated
   */
  EAttribute getNewExp_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.NewExp#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see edu.ustb.cmp.miniJava.NewExp#getParams()
   * @see #getNewExp()
   * @generated
   */
  EReference getNewExp_Params();

  /**
   * Returns the meta object for class '{@link edu.ustb.cmp.miniJava.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see edu.ustb.cmp.miniJava.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.Expression#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see edu.ustb.cmp.miniJava.Expression#getStatements()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Statements();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.Expression#getElseIf <em>Else If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Else If</em>'.
   * @see edu.ustb.cmp.miniJava.Expression#getElseIf()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_ElseIf();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ustb.cmp.miniJava.Expression#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Else</em>'.
   * @see edu.ustb.cmp.miniJava.Expression#getElse()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Else();

  /**
   * Returns the meta object for the attribute '{@link edu.ustb.cmp.miniJava.Expression#getConst <em>Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Const</em>'.
   * @see edu.ustb.cmp.miniJava.Expression#getConst()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Const();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Expression#getCe <em>Ce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ce</em>'.
   * @see edu.ustb.cmp.miniJava.Expression#getCe()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Ce();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Expression#getJe <em>Je</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Je</em>'.
   * @see edu.ustb.cmp.miniJava.Expression#getJe()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Je();

  /**
   * Returns the meta object for the containment reference '{@link edu.ustb.cmp.miniJava.Expression#getNe <em>Ne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ne</em>'.
   * @see edu.ustb.cmp.miniJava.Expression#getNe()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Ne();

  /**
   * Returns the meta object for enum '{@link edu.ustb.cmp.miniJava.Domain <em>Domain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Domain</em>'.
   * @see edu.ustb.cmp.miniJava.Domain
   * @generated
   */
  EEnum getDomain();

  /**
   * Returns the meta object for enum '{@link edu.ustb.cmp.miniJava.ExtraAttr <em>Extra Attr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Extra Attr</em>'.
   * @see edu.ustb.cmp.miniJava.ExtraAttr
   * @generated
   */
  EEnum getExtraAttr();

  /**
   * Returns the meta object for enum '{@link edu.ustb.cmp.miniJava.BooleanExp <em>Boolean Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Boolean Exp</em>'.
   * @see edu.ustb.cmp.miniJava.BooleanExp
   * @generated
   */
  EEnum getBooleanExp();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MiniJavaFactory getMiniJavaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.MiniJavaImpl <em>Mini Java</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getMiniJava()
     * @generated
     */
    EClass MINI_JAVA = eINSTANCE.getMiniJava();

    /**
     * The meta object literal for the '<em><b>Package</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINI_JAVA__PACKAGE = eINSTANCE.getMiniJava_Package();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINI_JAVA__IMPORTS = eINSTANCE.getMiniJava_Imports();

    /**
     * The meta object literal for the '<em><b>Mainclass</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINI_JAVA__MAINCLASS = eINSTANCE.getMiniJava_Mainclass();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINI_JAVA__CLASSES = eINSTANCE.getMiniJava_Classes();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.PackageDeclImpl <em>Package Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.PackageDeclImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getPackageDecl()
     * @generated
     */
    EClass PACKAGE_DECL = eINSTANCE.getPackageDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE_DECL__NAME = eINSTANCE.getPackageDecl_Name();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.ImportDeclImpl <em>Import Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.ImportDeclImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getImportDecl()
     * @generated
     */
    EClass IMPORT_DECL = eINSTANCE.getImportDecl();

    /**
     * The meta object literal for the '<em><b>Anchor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT_DECL__ANCHOR = eINSTANCE.getImportDecl_Anchor();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.MainClassDeclImpl <em>Main Class Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.MainClassDeclImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getMainClassDecl()
     * @generated
     */
    EClass MAIN_CLASS_DECL = eINSTANCE.getMainClassDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN_CLASS_DECL__NAME = eINSTANCE.getMainClassDecl_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_CLASS_DECL__STATEMENTS = eINSTANCE.getMainClassDecl_Statements();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.ClassDeclImpl <em>Class Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.ClassDeclImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getClassDecl()
     * @generated
     */
    EClass CLASS_DECL = eINSTANCE.getClassDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_DECL__NAME = eINSTANCE.getClassDecl_Name();

    /**
     * The meta object literal for the '<em><b>Super Class</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECL__SUPER_CLASS = eINSTANCE.getClassDecl_SuperClass();

    /**
     * The meta object literal for the '<em><b>Implementz</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECL__IMPLEMENTZ = eINSTANCE.getClassDecl_Implementz();

    /**
     * The meta object literal for the '<em><b>Members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECL__MEMBERS = eINSTANCE.getClassDecl_Members();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.VariableDeclImpl <em>Variable Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.VariableDeclImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getVariableDecl()
     * @generated
     */
    EClass VARIABLE_DECL = eINSTANCE.getVariableDecl();

    /**
     * The meta object literal for the '<em><b>Var Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECL__VAR_TYPE = eINSTANCE.getVariableDecl_VarType();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECL__VALUE = eINSTANCE.getVariableDecl_Value();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.ParameterImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.MethodDeclImpl <em>Method Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.MethodDeclImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getMethodDecl()
     * @generated
     */
    EClass METHOD_DECL = eINSTANCE.getMethodDecl();

    /**
     * The meta object literal for the '<em><b>Domain</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DECL__DOMAIN = eINSTANCE.getMethodDecl_Domain();

    /**
     * The meta object literal for the '<em><b>Extra</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DECL__EXTRA = eINSTANCE.getMethodDecl_Extra();

    /**
     * The meta object literal for the '<em><b>Ret Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DECL__RET_TYPE = eINSTANCE.getMethodDecl_RetType();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_DECL__PARAMS = eINSTANCE.getMethodDecl_Params();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_DECL__STATEMENTS = eINSTANCE.getMethodDecl_Statements();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.MemberImpl <em>Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.MemberImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getMember()
     * @generated
     */
    EClass MEMBER = eINSTANCE.getMember();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMBER__NAME = eINSTANCE.getMember_Name();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.StatementImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Var Def</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__VAR_DEF = eINSTANCE.getStatement_VarDef();

    /**
     * The meta object literal for the '<em><b>Assign</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__ASSIGN = eINSTANCE.getStatement_Assign();

    /**
     * The meta object literal for the '<em><b>If Stat</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__IF_STAT = eINSTANCE.getStatement_IfStat();

    /**
     * The meta object literal for the '<em><b>While Stat</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__WHILE_STAT = eINSTANCE.getStatement_WhileStat();

    /**
     * The meta object literal for the '<em><b>Ret Stat</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__RET_STAT = eINSTANCE.getStatement_RetStat();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.LValueExpImpl <em>LValue Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.LValueExpImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getLValueExp()
     * @generated
     */
    EClass LVALUE_EXP = eINSTANCE.getLValueExp();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LVALUE_EXP__ID = eINSTANCE.getLValueExp_Id();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LVALUE_EXP__EXP = eINSTANCE.getLValueExp_Exp();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LVALUE_EXP__INDEX = eINSTANCE.getLValueExp_Index();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.AssignmentsImpl <em>Assignments</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.AssignmentsImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getAssignments()
     * @generated
     */
    EClass ASSIGNMENTS = eINSTANCE.getAssignments();

    /**
     * The meta object literal for the '<em><b>Left Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENTS__LEFT_VALUE = eINSTANCE.getAssignments_LeftValue();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENTS__EXPRESSION = eINSTANCE.getAssignments_Expression();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.IfStatementsImpl <em>If Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.IfStatementsImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getIfStatements()
     * @generated
     */
    EClass IF_STATEMENTS = eINSTANCE.getIfStatements();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.ElseIfStatementsImpl <em>Else If Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.ElseIfStatementsImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getElseIfStatements()
     * @generated
     */
    EClass ELSE_IF_STATEMENTS = eINSTANCE.getElseIfStatements();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.ElseStatementImpl <em>Else Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.ElseStatementImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getElseStatement()
     * @generated
     */
    EClass ELSE_STATEMENT = eINSTANCE.getElseStatement();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELSE_STATEMENT__STATEMENTS = eINSTANCE.getElseStatement_Statements();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.WhileStatementsImpl <em>While Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.WhileStatementsImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getWhileStatements()
     * @generated
     */
    EClass WHILE_STATEMENTS = eINSTANCE.getWhileStatements();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.ReturnStatementsImpl <em>Return Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.ReturnStatementsImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getReturnStatements()
     * @generated
     */
    EClass RETURN_STATEMENTS = eINSTANCE.getReturnStatements();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETURN_STATEMENTS__EXP = eINSTANCE.getReturnStatements_Exp();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.CalcExpImpl <em>Calc Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.CalcExpImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getCalcExp()
     * @generated
     */
    EClass CALC_EXP = eINSTANCE.getCalcExp();

    /**
     * The meta object literal for the '<em><b>Left Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALC_EXP__LEFT_NAME = eINSTANCE.getCalcExp_LeftName();

    /**
     * The meta object literal for the '<em><b>Left Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALC_EXP__LEFT_NUM = eINSTANCE.getCalcExp_LeftNum();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALC_EXP__OP = eINSTANCE.getCalcExp_Op();

    /**
     * The meta object literal for the '<em><b>Right Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALC_EXP__RIGHT_NAME = eINSTANCE.getCalcExp_RightName();

    /**
     * The meta object literal for the '<em><b>Right Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALC_EXP__RIGHT_NUM = eINSTANCE.getCalcExp_RightNum();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.CompareExpImpl <em>Compare Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.CompareExpImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getCompareExp()
     * @generated
     */
    EClass COMPARE_EXP = eINSTANCE.getCompareExp();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARE_EXP__ID = eINSTANCE.getCompareExp_Id();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARE_EXP__OP = eINSTANCE.getCompareExp_Op();

    /**
     * The meta object literal for the '<em><b>Other1</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARE_EXP__OTHER1 = eINSTANCE.getCompareExp_Other1();

    /**
     * The meta object literal for the '<em><b>Other2</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARE_EXP__OTHER2 = eINSTANCE.getCompareExp_Other2();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.BasicJudgeImpl <em>Basic Judge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.BasicJudgeImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getBasicJudge()
     * @generated
     */
    EClass BASIC_JUDGE = eINSTANCE.getBasicJudge();

    /**
     * The meta object literal for the '<em><b>BE</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASIC_JUDGE__BE = eINSTANCE.getBasicJudge_BE();

    /**
     * The meta object literal for the '<em><b>Cmp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BASIC_JUDGE__CMP = eINSTANCE.getBasicJudge_Cmp();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.JudgeExpImpl <em>Judge Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.JudgeExpImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getJudgeExp()
     * @generated
     */
    EClass JUDGE_EXP = eINSTANCE.getJudgeExp();

    /**
     * The meta object literal for the '<em><b>Bj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JUDGE_EXP__BJ = eINSTANCE.getJudgeExp_Bj();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.NewExpImpl <em>New Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.NewExpImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getNewExp()
     * @generated
     */
    EClass NEW_EXP = eINSTANCE.getNewExp();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NEW_EXP__NAME = eINSTANCE.getNewExp_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEW_EXP__PARAMS = eINSTANCE.getNewExp_Params();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.impl.ExpressionImpl
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__STATEMENTS = eINSTANCE.getExpression_Statements();

    /**
     * The meta object literal for the '<em><b>Else If</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__ELSE_IF = eINSTANCE.getExpression_ElseIf();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__ELSE = eINSTANCE.getExpression_Else();

    /**
     * The meta object literal for the '<em><b>Const</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__CONST = eINSTANCE.getExpression_Const();

    /**
     * The meta object literal for the '<em><b>Ce</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__CE = eINSTANCE.getExpression_Ce();

    /**
     * The meta object literal for the '<em><b>Je</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__JE = eINSTANCE.getExpression_Je();

    /**
     * The meta object literal for the '<em><b>Ne</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__NE = eINSTANCE.getExpression_Ne();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.Domain <em>Domain</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.Domain
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getDomain()
     * @generated
     */
    EEnum DOMAIN = eINSTANCE.getDomain();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.ExtraAttr <em>Extra Attr</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.ExtraAttr
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getExtraAttr()
     * @generated
     */
    EEnum EXTRA_ATTR = eINSTANCE.getExtraAttr();

    /**
     * The meta object literal for the '{@link edu.ustb.cmp.miniJava.BooleanExp <em>Boolean Exp</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ustb.cmp.miniJava.BooleanExp
     * @see edu.ustb.cmp.miniJava.impl.MiniJavaPackageImpl#getBooleanExp()
     * @generated
     */
    EEnum BOOLEAN_EXP = eINSTANCE.getBooleanExp();

  }

} //MiniJavaPackage
