/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.ustb.cmp.miniJava.MiniJavaPackage
 * @generated
 */
public interface MiniJavaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MiniJavaFactory eINSTANCE = edu.ustb.cmp.miniJava.impl.MiniJavaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Mini Java</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mini Java</em>'.
   * @generated
   */
  MiniJava createMiniJava();

  /**
   * Returns a new object of class '<em>Package Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Package Decl</em>'.
   * @generated
   */
  PackageDecl createPackageDecl();

  /**
   * Returns a new object of class '<em>Import Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import Decl</em>'.
   * @generated
   */
  ImportDecl createImportDecl();

  /**
   * Returns a new object of class '<em>Main Class Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Class Decl</em>'.
   * @generated
   */
  MainClassDecl createMainClassDecl();

  /**
   * Returns a new object of class '<em>Class Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Decl</em>'.
   * @generated
   */
  ClassDecl createClassDecl();

  /**
   * Returns a new object of class '<em>Variable Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Decl</em>'.
   * @generated
   */
  VariableDecl createVariableDecl();

  /**
   * Returns a new object of class '<em>Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter</em>'.
   * @generated
   */
  Parameter createParameter();

  /**
   * Returns a new object of class '<em>Method Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Decl</em>'.
   * @generated
   */
  MethodDecl createMethodDecl();

  /**
   * Returns a new object of class '<em>Member</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Member</em>'.
   * @generated
   */
  Member createMember();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>LValue Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LValue Exp</em>'.
   * @generated
   */
  LValueExp createLValueExp();

  /**
   * Returns a new object of class '<em>Assignments</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignments</em>'.
   * @generated
   */
  Assignments createAssignments();

  /**
   * Returns a new object of class '<em>If Statements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Statements</em>'.
   * @generated
   */
  IfStatements createIfStatements();

  /**
   * Returns a new object of class '<em>Else If Statements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Else If Statements</em>'.
   * @generated
   */
  ElseIfStatements createElseIfStatements();

  /**
   * Returns a new object of class '<em>Else Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Else Statement</em>'.
   * @generated
   */
  ElseStatement createElseStatement();

  /**
   * Returns a new object of class '<em>While Statements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>While Statements</em>'.
   * @generated
   */
  WhileStatements createWhileStatements();

  /**
   * Returns a new object of class '<em>Return Statements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Return Statements</em>'.
   * @generated
   */
  ReturnStatements createReturnStatements();

  /**
   * Returns a new object of class '<em>Calc Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Calc Exp</em>'.
   * @generated
   */
  CalcExp createCalcExp();

  /**
   * Returns a new object of class '<em>Compare Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Compare Exp</em>'.
   * @generated
   */
  CompareExp createCompareExp();

  /**
   * Returns a new object of class '<em>Basic Judge</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Basic Judge</em>'.
   * @generated
   */
  BasicJudge createBasicJudge();

  /**
   * Returns a new object of class '<em>Judge Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Judge Exp</em>'.
   * @generated
   */
  JudgeExp createJudgeExp();

  /**
   * Returns a new object of class '<em>New Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>New Exp</em>'.
   * @generated
   */
  NewExp createNewExp();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MiniJavaPackage getMiniJavaPackage();

} //MiniJavaFactory
