/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.cmp.miniJava.Statement#getVarDef <em>Var Def</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Statement#getAssign <em>Assign</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Statement#getIfStat <em>If Stat</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Statement#getWhileStat <em>While Stat</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.Statement#getRetStat <em>Ret Stat</em>}</li>
 * </ul>
 *
 * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Var Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Def</em>' containment reference.
   * @see #setVarDef(VariableDecl)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getStatement_VarDef()
   * @model containment="true"
   * @generated
   */
  VariableDecl getVarDef();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Statement#getVarDef <em>Var Def</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Def</em>' containment reference.
   * @see #getVarDef()
   * @generated
   */
  void setVarDef(VariableDecl value);

  /**
   * Returns the value of the '<em><b>Assign</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assign</em>' containment reference.
   * @see #setAssign(Assignments)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getStatement_Assign()
   * @model containment="true"
   * @generated
   */
  Assignments getAssign();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Statement#getAssign <em>Assign</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assign</em>' containment reference.
   * @see #getAssign()
   * @generated
   */
  void setAssign(Assignments value);

  /**
   * Returns the value of the '<em><b>If Stat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Stat</em>' containment reference.
   * @see #setIfStat(IfStatements)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getStatement_IfStat()
   * @model containment="true"
   * @generated
   */
  IfStatements getIfStat();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Statement#getIfStat <em>If Stat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If Stat</em>' containment reference.
   * @see #getIfStat()
   * @generated
   */
  void setIfStat(IfStatements value);

  /**
   * Returns the value of the '<em><b>While Stat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>While Stat</em>' containment reference.
   * @see #setWhileStat(WhileStatements)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getStatement_WhileStat()
   * @model containment="true"
   * @generated
   */
  WhileStatements getWhileStat();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Statement#getWhileStat <em>While Stat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>While Stat</em>' containment reference.
   * @see #getWhileStat()
   * @generated
   */
  void setWhileStat(WhileStatements value);

  /**
   * Returns the value of the '<em><b>Ret Stat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ret Stat</em>' containment reference.
   * @see #setRetStat(ReturnStatements)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getStatement_RetStat()
   * @model containment="true"
   * @generated
   */
  ReturnStatements getRetStat();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.Statement#getRetStat <em>Ret Stat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ret Stat</em>' containment reference.
   * @see #getRetStat()
   * @generated
   */
  void setRetStat(ReturnStatements value);

} // Statement
