/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.cmp.miniJava.VariableDecl#getVarType <em>Var Type</em>}</li>
 *   <li>{@link edu.ustb.cmp.miniJava.VariableDecl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getVariableDecl()
 * @model
 * @generated
 */
public interface VariableDecl extends Member
{
  /**
   * Returns the value of the '<em><b>Var Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Type</em>' attribute.
   * @see #setVarType(String)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getVariableDecl_VarType()
   * @model
   * @generated
   */
  String getVarType();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.VariableDecl#getVarType <em>Var Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Type</em>' attribute.
   * @see #getVarType()
   * @generated
   */
  void setVarType(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getVariableDecl_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link edu.ustb.cmp.miniJava.VariableDecl#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // VariableDecl
