/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ustb.cmp.miniJava.MiniJavaPackage#getWhileStatements()
 * @model
 * @generated
 */
public interface WhileStatements extends EObject
{
} // WhileStatements
