/**
 * generated by Xtext 2.25.0
 */
package edu.ustb.cmp.miniJava.impl;

import edu.ustb.cmp.miniJava.ElseIfStatements;
import edu.ustb.cmp.miniJava.MiniJavaPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Else If Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ElseIfStatementsImpl extends MinimalEObjectImpl.Container implements ElseIfStatements
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElseIfStatementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MiniJavaPackage.Literals.ELSE_IF_STATEMENTS;
  }

} //ElseIfStatementsImpl
